### ISSUE TITLE
Make data available for download

### ISSUE THREAD

**Issue by cverluise** [cverluise/PatCit#16]
Data is available on BigQuery but some users might want to extract the full (part of?) database to work with their own tools. 

## Feature description

The feature might actually come in different flavours:

- full extraction
- partial extraction based on publication year, a list of patents, a list of NPL, etc

Any there use case is most welcome and will be addressed asap - based on the amount of resources required

**Comment by gderasse** [comment]
I can think of these three uses cases:
1. Extract information for a selected set of patents (a patent list provided by the user)
2. Extract information for a selected set of journals
3. Extract information for a given paper

**Comment by cverluise** [comment]
Bulk download on:

- Zenodo: https://zenodo.org/record/3710994
- Google storage: https://console.cloud.google.com/storage/browser/patcit

Closing the issue.
