### ISSUE TITLE
Add link to patstat appln_id

### ISSUE THREAD

**Issue by Antoberge** [cverluise/PatCit#34]
## Patstat and PatCit

In most case, researchers use Patstat to explore patent level information. The main identifiying variable from Patstat is called appln_id. This variable can then be linked to the many different tables of Patstat, and does not change in subsequent release of Patstat.

## What could be done

appln_id can be linked to the publication number, which is the identifier in the current version of PatCit (v2.0) using Patstat table tls211. There is a one to one mapping between the appln_id and the final publication number. It would be useful to have a new entry in the array cited_by adding the corresponding appln_id

Thanks

**Comment by cverluise** [comment]
Hello, this is now done in v0.3 🎉 .
Closing now, fee free to reopen if needed. 
Cheers
