### ISSUE TITLE
Naming of the files in the tar archives

### ISSUE THREAD

**Issue by n3ssuno** [cverluise/PatCit#36]
## Naming of the files in the tar archives

Hi and, first of all, thanks for this tremendous job!

I downloaded both the frontpage_bibliographicalreference.tar and intext_bibliographicalreference.tar files.

I untar both in a folder. If I'm not wrong, the name of both the file lists in the two tar archives starts from 0. Therefore, the second time I overwrote the fist files.

Why not to use different names for the files, like frontpage_bibliographicalreference_000000000000.jsonl.gz instead of bibliographical_reference_000000000000.jsonl.gz?

Does this rise an issue with the name of the database tables? In this case, maybe would be worth just to write a warning in the documentation so that people know that it's needed to use two subfolders, one for the front-page citations and one for the in-text ones.

**Comment by cverluise** [comment]
Hello @n3ssuno, 
thanks for noticing this issue. 
I'll add a note to the next version of the doc. 
Thanks!
